# Registers all source files used by the ESP32
idf_component_register(
    SRCS
        "main.c"
        "wifi.c"
        "uart_test.c"
        "tft_display.c"
        "tft_graphics.c"
        "tft_font.c"
        "encoder.c"
        "ui_common.c"
        "ui_home.c"
        "ui_control.c"
        "ui_measurements.c"
        "ui_faults.c"
        "ui_settings.c"
        "ui_task.c"
    INCLUDE_DIRS
        "."
)